elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
  volumes:
    - /var/lib/elasticsearch/data/:/usr/share/elasticsearch/data/
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
  environment:
    - LS_HEAP_SIZE=2048m
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
